server:
  port: 8089
spring:
  datasource:
    url: jdbc:mybatis:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  jpa:
    database: mybatis
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      path: /mybatis-console
      enabled: true